# Generated by Django 4.1.13 on 2024-08-07 04:53

from django.db import migrations, models
import djongo.models.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "_id",
                    djongo.models.fields.ObjectIdField(
                        auto_created=True,
                        db_column="_id",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("BrandName", models.CharField(db_column="BrandName", max_length=255)),
                ("ProductID", models.CharField(db_column="ProductID", max_length=255)),
                (
                    "ProductName",
                    models.CharField(db_column="ProductName", max_length=255),
                ),
                ("BrandDesc", models.TextField(db_column="BrandDesc")),
                (
                    "ProductSize",
                    models.CharField(db_column="ProductSize", max_length=255),
                ),
                ("Currency", models.CharField(db_column="Currancy", max_length=10)),
                ("MRP", models.FloatField(db_column="MRP")),
                ("SellPrice", models.FloatField(db_column="SellPrice")),
                ("Discount", models.CharField(db_column="Discount", max_length=50)),
                ("Category", models.CharField(db_column="Category", max_length=255)),
            ],
            options={
                "db_table": "products",
            },
        ),
    ]
